#!/bin/dash
# Ver.iwm20230304
#--------------------------------------------------------------------------------
# 使用例
#   dash: echo $(iwm_RtnPkgManager)
#   ruby: puts %x(iwm_RtnPkgManager)
#--------------------------------------------------------------------------------
# 絶対パスで検索
for _s1 in "/usr/bin/apt" "/usr/bin/dnf"
do
	if [ -e "${_s1}" ]
	then
		echo -n "${_s1}"
		exit
	fi
done
# 該当ないとき "" を返す
echo -n ""
